### ISSUE TITLE
Working portaudio.so for Android

### ISSUE THREAD

**Issue by fredvs** [Gundersanne/pa-android-tests#1]
Hello and wow for that marvelous project.

I did try the libportaudio.so library included in you package but for each method called my application crash.

Also I did try to cross-compile portaudio with your script but without luck.

I am the maintainer of uos (https://github.com/fredvs/uoslib).

libuos.so for Android can deal with libsndfile.so and libmpg123.so ==> the libraries compiled for Android work like charm.

But I fail to find (or compile) portaudio for Android.

And without portaudio, uos is not very noisy on Andoid machines ... .;)

Many thanks.

Fre;D

**Comment by croissanne** [comment]
Hai & thank you :)

Can you provide a stacktrace? 

The compiled libraries in this repository might be a bit out of date. Since a couple of bugs have been fixed. If you're opening only audio input (without outputstream) it won't work. I'll update these soon.

Cmake support was also added https://github.com/Gundersanne/portaudio_opensles/pull/3 if that's easier. Where exactly does the crosscompiling fail?

**Comment by fredvs** [comment]
Hello and thanks for answer.

After a long and hard battle, I finally was able to cross-compile portaudio.

One of the combat was to avoid the error message while linking:

>  ld: error: cannot find -lpthread

The trick was to edit MakeFile and delete all **-pthread** parameter.
That way the linking worked.
But I did not try to use it yet, this will be the surprise of tonight.

By the way, I noted that portaudio create a thread each time that **Pa_OpenStream()** is called.
Do you think that it could be possible to ask portaudio (changing some code) to not create a thread?

This because in the main application, a thread is created at creation of each Player and so no need to have 2 threads for only one player (because Pa_OpenStream() create a other thread inside the Player thread) .

I hope that you did understand.

Last thing, I did see that you are using a other audio library to load portaudio for Android (opensles).

Does it mean that portaudio "alone" will not work on Android?

In attachent,  libportaudio.so cross-compiled for Android without -pthread (not yet tested).

Thanks.

Fre;D
[libportaudio.so.tar.gz](https://github.com/Gundersanne/pa-android-tests/files/1685791/libportaudio.so.tar.gz)

**Comment by croissanne** [comment]
> edit MakeFile

There should be no need to edit the makefile directly. I added support for android in configure.in. It shouldn't link against pthread. You can try running autoreconf before running the crosscompile script just to be sure you have the latest configure script. The shared objects I uploaded here also do not link against pthread.

OpenSL ES is a native android api for audio. Portaudio offers a uniform api for several 'backends' (=hostapis). On android the standard linux ones (alsa, etc...) are not available (or at least not part of the public apis). Portaudio "alone" wouldn't work on any platform, as you need the hostapi to actually output sound. It seems the so you attached doesn't link against opensles so it won't work. Are you using the provided script(crosscompile_portaudio_android.sh) ? Since this script should do everything correctly.

On the topic of threading I'm not sure I follow you. The opensl es hostapi  starts a thread if async audio processing was requested (i.e. no callback was provided). If opened blocking it will not create that thread. Anything beyond that (portaudio internals, android internals) I don't really have any control over.

**Comment by fredvs** [comment]
Hello and many thanks for answer.

I did try the library of yesterday compiled with portaudio-trunck.
This one was created by a custom MakeFile + the help of your script.

Perfect, trying on Android, LoadLibrary(portaudio) is ok and all the methods are working.
But, like you perfectly explained, Pa_GetDeviceCount() is always = 0 ;(

> Are you using the provided script(crosscompile_portaudio_android.sh) ? 

Huh, I did try without success, so I did a custom one inspired by yours.
Must OpenSL ES be installed ?
Does it need some source to compile portaudio with OpenSL ES access ?

But yes, there is hope.  Now that I understand better how it works and with your high value advices, I am sure it will work.

OK, I will retry from scratch using your code (not from trunk) and try to make portaudio recognize OpenSL.

> On the topic of threading I'm not sure I follow you.

I agree it is difficult to explain.

> starts a thread if async audio processing was requested (i.e. no callback was provided).

Is it not the work of the main application to create a thread and let portaudio do all his job inside that thread ?

But this is detail, portaudio works fabulous on all the platform tested.

Many thanks for your code and help.

Fre;D

**Comment by fredvs** [comment]
Re-hello.

Yeeep, it works ---> HostAPI: android OpenGLES. ;)

I did try your source + a adapted script to my system, it compiles and no there is a new device and a default device recognized by portaudio on Android.

I did not try yet to play files using uos + portaudio + sndfile + mpg123 - soundtouch + aac libraries.

But all work now.

I am totally beginner with Android, to test it, I have to understand how to access files from SD, ram or source.

So many thanks for your help.

I will give you news + a apk demo asap.

Fre;D

**Comment by fredvs** [comment]
Hello.

Ok, **libportaudio.so** compiled with your code did work ;)

Many methods are working including infos of default device.

`Pa_Initialize() `is ok too.

Sadly the result of `Pa_OpenDefaultStream(stream, 2, 2, paInt16, 48000, 512, nil, nil)` is always -1, even with other parameters.

I am blocked

Included compiled the libportaudio.so used.
[libportaudio.so.tar.gz](https://github.com/Gundersanne/pa-android-tests/files/1688005/libportaudio.so.tar.gz)

Fre;D

**Comment by croissanne** [comment]
Hey,

> portaudio-trunck

Android support wasn't merged. So for now only my source will work on android :)

> Is it not the work of the main application to create a thread and let portaudio do all his job inside that thread ?

Portaudio already does this for you. If you want asynchronous audio processing simply provide a callback. This will be called each time the hostapi needs more audio data.

> Sadly the result of Pa_OpenDefaultStream(stream, 2, 2, paInt16, 48000, 512, nil, nil) is always -1, even with other parameters.

Without some context it'll be very hard to say what's wrong. 

>Must OpenSL ES be installed ?
Does it need some source to compile portaudio with OpenSL ES access ?

Opensles is part of android starting api 9.

**Comment by fredvs** [comment]
Hello.

> Android support wasn't merged. So for now only my source will work on android :)

Ooops, I did not know that.  
So WOW x 1000 for your project, it will surely be a indispensable must-have for the Android world.

>> Sadly the result of `Pa_OpenDefaultStream(stream, 2, 2, paInt16, 48000, 512, nil, nil) `is always -1, even with other parameters.

 > Without some context it'll be very hard to say what's wrong.

In my case, all the portaudio-methods are loaded by **libuos.so**.

**libuos.so** works and was tested deeply as Java native library (in Linux+FreeBSD+Windows os).
All the demos in the **uos** package are working.

I try to make run a custom sinewave Android demo.

To resume, the first methods used in **libuos.so** (in Pascal).

1) `LoadLibrary('libportaudio.so')`  => OK

1) `Pa_Initialize()`.  => OK

2) `Pa_OpenDefaultStream(stream, 2, 2, paInt16, 48000, 512, nil, nil)` => Not OK err = -1.

Included apk + source demo that use **libuos.so + libportaudio.so + libsnfile.so + libmpg123.so**.

PS: In the demo, there is no sound (because of` Pa_OpenDefaultStream() = -1`).
But you will see that all the other methods are working.

Fre;D

[main.tar.gz](https://github.com/Gundersanne/pa-android-tests/files/1690055/main.tar.gz)
[app-debug.apk.tar.gz](https://github.com/Gundersanne/pa-android-tests/files/1690086/app-debug.apk.tar.gz)

**Comment by fredvs** [comment]
Re-hello and sorry to monopolize that topic...
But I do not like to leave a negative advice...

Here good news  ===> I get sound !
Not yet perfect, but the sinewave demo works.
Strangely, the value of parameters used for  Pa_OpenStream() are not the same as other os.
I have to discover how to tune it.

But it works, that is excellent news.

Many thanks for your brillant work and please, keep on.

Fre;D

PS: Included demo apk with sound.
[app-debug.apk.tar.gz](https://github.com/Gundersanne/pa-android-tests/files/1692369/app-debug.apk.tar.gz)

**Comment by croissanne** [comment]
Hey, 
glad to hear that it's working.

> Strangely, the value of parameters used for Pa_OpenStream() are not the same as other os.

Depending on device there are 'ideal' parameters. You can query those like so:
```Java
AudioManager audio = (AudioManager) getSystemService(Context.AUDIO_SERVICE);
String sampleRate = audio.getProperty(AudioManager.PROPERTY_OUTPUT_SAMPLE_RATE);
String bufferSize = audio.getProperty(AudioManager.PROPERTY_OUTPUT_FRAMES_PER_BUFFER);
```

**Comment by fredvs** [comment]
Hello Gundersane.

Many thanks for your answer.

I did many, many test.  But I get alway a half sound, I mean only the half of the buffer is played with `Pa_WriteStream()`.  
I did try many combination but only if the buffer is big ( > 65536 ) and Frames parameter of `Pa_OpenStream()` = length of the buffer div channels give a correct full sound.
But strangely a long delay appears before the sound is produced.

I will try with your advices of AudioManager audio (thanks for this), maybe it will solve everything.

Other thing, for me, `Pa_OpenDefaultStream` gives always -1 as result but `Pa_OpenStream `is working, even using the same parameters used by `Pa_OpenDefaultStream`.

Huh, about the "masked thread", I do not want to annoy you with this but here result of debugger:
(This with or without using callback.)

- Before execute `Pa_OpenStream()` ==> running threads (only 1 thread = the main):

> #0  6060 unknown "consoleplay" 0x0000000000400e71 in ?? ()

- After execute `Pa_OpenStream()` ==> running threads (2 threads):

> #0  6060 unknown "consoleplay" 0x0000000000400e71 in ?? ()
> #1  6070 unknown "threaded-ml" 0x00007ffff76dfc9d in poll () at ../sysdeps/unix/syscall-template.S:81

Details of "threaded-ml":

> #0  F76DFC9D syscall-template.S:81 poll()
> #1  F4DFB031 :0 ??()
> #2  F4DEC83C :0 pa_mainloop_poll()
> #3  F4DECECE :0 pa_mainloop_iterate()
> #4  F4DECF80 :0 pa_mainloop_run()
> #5  F4DFAFE3 :0 ??()
> #6  F499EF08 :0 ??()
> #7  F7BC4184 pthread_create.c:312 start_thread(arg=0x7fffeaf97700)
> #8  F76ED03D clone.S:111 clone()

But maybe it is necessary for PortAudio to create/have his own thread (and not use the thread created by the main application), so forget this.

Many thanks.

Fre;D

**Comment by fredvs** [comment]
Hello.

OK, i did use your code: --> sampleRate = 48000 and bufferSize = 256.

But sadly, even using that parameters (and lot of others around this) gives always the same problem of only the half of the buffer played at each loop of` Pa_WriteStream()`.

The good news is that the quality of sound is perfect (even with float32 resolution) for that half played buffer.

Fre;D

**Comment by QaYeDev** [comment]
كيف استدعيها من بايثون؟؟؟؟؟؟؟؟؟؟ PortAudio = JavaClass('libportaudio')
لم تنفع معي كيف استدعيها يا رفاق؟؟؟؟؟
