### ISSUE TITLE
-bash: /android-ndk-r9b/ndk-build: No such file or directory

### ISSUE THREAD

**Issue by Zeesy** [Gundersanne/pa-android-tests#2]
Thank you for this very useful project! I am caught on [Building the Examples](https://github.com/Gundersanne/pa-android-tests#building-the-examples). I installed Android NDK r9b using wget without a problem. However, android-ndk-r9b does not seem to exist anywhere.

After running `export ANDROID_NDK_ROOT=/root/pa-android-tests/<folder>/<command was run from>/jni/android-ndk-r9b && $ANDROID_NDK_ROOT/ndk-build
`
I get the error message `-bash: /root/pa-android-tests/<folder>/<command was run from>/jni/ndk-build: No such file or directory`

When I run `readlink -f android-ndk-r9b` 
I get `/root/pa-android-tests/<folder>/<command was run from>/jni/android-ndk-r9b`

and when I run `realpath -e android-ndk-r9b` 
I get `realpath: android-ndk-r9b: No such file or directory`

I realize that this is just as likely an issue with my not knowing how to run the export command as it could be a bug. I took a look at [Working portaudio.so for Android #1](https://github.com/Gundersanne/pa-android-tests/issues/1) but it's a bit over my head. Any advice would be much appreciated!

**Comment by Zeesy** [comment]
To partially answer my own question - I did not unzip the `tar.bz2` file. As a result, there were no examples to build. For anyone else who is a novice like me, try:

`wget -c http://dl.google.com/android/ndk/android-ndk-r9b-linux-x86_64.tar.bz2`

then

`tar -xvjf android-ndk-r9b-linux-x86_64.tar.bz2`

I then went up to `~/pa-android-tests/playrecord/jni` and ran `export ANDROID_NDK_ROOT=~/android-ndk-r9b && $ANDROID_NDK_ROOT/ndk-build`

Success!

**Comment by eKABIA** [comment]
hi all somebody can help for building in any android platform ? 
x86 , x86_64 , armeabi etc..
